package exceptionn.in;

public class Demo {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		int i = 0;
		int j = 0;
		
		int num[] = new int[5];
		
		try {
			j = 18/i;
			System.out.println(num[1]);
			System.out.println(num[5]);
			
		} 
		catch (ArithmeticException e) {
			// TODO: handle exception
			System.out.println("Something went wrong..");
		}
	    catch (ArrayIndexOutOfBoundsException e) {
			// TODO: handle exception
			System.out.println("Stay in your Limit...");
		}
		
		System.out.println(j);
		System.out.println("The End");

	}

}
